### ISSUE TITLE
Crash when COFH stuff is installed without GeoStrata

### ISSUE THREAD

**Issue by rewbycraft** [da3dsoul/Additional-Buildcraft-Objects#41]
Basically, your ore-gen overrider assumes people have geostrata installed when they have CoFH mods installed. This is not always the case, resulting in this crash (using latest release, 4.0.5):

```
[12:34:31] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: Reika/GeoStrata/Registry/RockTypes
    at da3dsoul.scaryGen.generate.GeostrataGen.Ore.COFH.WorldGenMinableClusterOverride.generateBlock(WorldGenMinableClusterOverride.java:171) ~[WorldGenMinableClusterOverride.class:?]
    at da3dsoul.scaryGen.generate.GeostrataGen.Ore.COFH.WorldGenMinableClusterOverride.generateBlock(WorldGenMinableClusterOverride.java:159) ~[WorldGenMinableClusterOverride.class:?]
    at da3dsoul.scaryGen.generate.GeostrataGen.Ore.COFH.WorldGenMinableClusterOverride.func_76484_a(WorldGenMinableClusterOverride.java:114) ~[WorldGenMinableClusterOverride.class:?]
    at cofh.lib.world.feature.FeatureGenUniform.generateFeature(FeatureGenUniform.java:39) ~[FeatureGenUniform.class:?]
    at cofh.lib.world.feature.FeatureBase.generateFeature(FeatureBase.java:117) ~[FeatureBase.class:?]
    at cofh.core.world.WorldHandler.generateWorld(WorldHandler.java:242) ~[WorldHandler.class:?]
    at cofh.core.world.WorldHandler.generate(WorldHandler.java:205) ~[WorldHandler.class:?]
    at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112) ~[GameRegistry.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) ~[ms.class:?]
    at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1055) ~[apx.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) ~[ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) ~[ms.class:?]
    at net.minecraft.server.management.PlayerManager$PlayerInstance.<init>(PlayerManager.java:370) ~[mr.class:?]
    at net.minecraft.server.management.PlayerManager.func_72690_a(PlayerManager.java:97) ~[mq.class:?]
    at net.minecraft.server.management.PlayerManager.func_72691_b(PlayerManager.java:174) ~[mq.class:?]
    at net.minecraft.server.management.PlayerManager.func_72685_d(PlayerManager.java:267) ~[mq.class:?]
    at net.minecraft.server.management.ServerConfigurationManager.func_72358_d(ServerConfigurationManager.java:313) ~[oi.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:404) ~[nh.class:?]
    at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137) ~[jd.class:?]
    at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.func_148833_a(SourceFile:63) ~[je.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.ClassNotFoundException: Reika.GeoStrata.Registry.RockTypes
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_60]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_60]
    ... 27 more
Caused by: java.lang.NullPointerException
```

**Comment by da3dsoul** [comment]
In what context is it being used? ScaryGen? Custom use? etc?

**Comment by da3dsoul** [comment]
nvm I did that part stupid.
